"""complete legal practice operations

Revision ID: 840688cc9b0b
Revises: 20260828_0009
Create Date: 2026-08-29 18:39:45.927428
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '840688cc9b0b'
down_revision: Union[str, None] = '20260828_0009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_provider_credentials',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('account_reference', sa.String(length=128), nullable=False),
    sa.Column('api_token_encrypted', sa.Text(), nullable=True),
    sa.Column('webhook_secret_encrypted', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("purpose IN ('signature', 'payment')", name='ck_operation_provider_credentials_purpose'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purpose', 'provider', 'account_reference', name='uq_operation_provider_webhook_identity'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_operation_provider_credentials_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'purpose', 'provider', 'account_reference', name='uq_operation_provider_credential')
    )
    op.create_index(op.f('ix_operation_provider_credentials_tenant_id'), 'operation_provider_credentials', ['tenant_id'], unique=False)
    op.create_table('public_intake_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('form_title', sa.String(length=120), nullable=False),
    sa.Column('notice_version', sa.String(length=64), nullable=False),
    sa.Column('consent_version', sa.String(length=64), nullable=False),
    sa.Column('notice_url', sa.String(length=2048), nullable=True),
    sa.Column('allowed_origin', sa.String(length=2048), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_public_intake_configs_tenant_id'),
    sa.UniqueConstraint('tenant_id', name='uq_public_intake_configs_tenant'),
    sa.UniqueConstraint('token_hash', name='uq_public_intake_configs_token')
    )
    op.create_index(op.f('ix_public_intake_configs_tenant_id'), 'public_intake_configs', ['tenant_id'], unique=False)
    op.create_table('controladoria_workflow_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('case_type', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('version > 0', name='ck_controladoria_workflow_templates_version'),
    sa.ForeignKeyConstraint(['tenant_id', 'created_by_user_id'], ['users.tenant_id', 'users.id'], name='fk_controladoria_workflow_templates_creator_tenant'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_controladoria_workflow_templates_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'name', 'version', name='uq_controladoria_workflow_templates_name_version')
    )
    op.create_index(op.f('ix_controladoria_workflow_templates_case_type'), 'controladoria_workflow_templates', ['case_type'], unique=False)
    op.create_index(op.f('ix_controladoria_workflow_templates_is_active'), 'controladoria_workflow_templates', ['is_active'], unique=False)
    op.create_index(op.f('ix_controladoria_workflow_templates_tenant_id'), 'controladoria_workflow_templates', ['tenant_id'], unique=False)
    op.create_table('controladoria_monitoring_subscriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('source_kind', sa.String(length=16), nullable=False),
    sa.Column('tribunal', sa.String(length=20), nullable=False),
    sa.Column('process_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=100), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=False),
    sa.Column('updated_by_user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source_kind IN ('datajud')", name='ck_controladoria_monitoring_subscriptions_source_kind'),
    sa.CheckConstraint("status IN ('active', 'paused', 'disabled')", name='ck_controladoria_monitoring_subscriptions_status'),
    sa.ForeignKeyConstraint(['tenant_id', 'case_id'], ['workspace_cases.tenant_id', 'workspace_cases.id'], name='fk_controladoria_monitoring_subscriptions_case_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'created_by_user_id'], ['users.tenant_id', 'users.id'], name='fk_controladoria_monitoring_subscriptions_creator_tenant'),
    sa.ForeignKeyConstraint(['tenant_id', 'updated_by_user_id'], ['users.tenant_id', 'users.id'], name='fk_controladoria_monitoring_subscriptions_updater_tenant'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'case_id', 'source_kind', 'tribunal', name='uq_controladoria_monitoring_subscriptions_case_source'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_controladoria_monitoring_subscriptions_tenant_id')
    )
    op.create_index(op.f('ix_controladoria_monitoring_subscriptions_case_id'), 'controladoria_monitoring_subscriptions', ['case_id'], unique=False)
    op.create_index(op.f('ix_controladoria_monitoring_subscriptions_status'), 'controladoria_monitoring_subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_controladoria_monitoring_subscriptions_tenant_id'), 'controladoria_monitoring_subscriptions', ['tenant_id'], unique=False)
    op.create_table('controladoria_workflow_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('template_name', sa.String(length=200), nullable=False),
    sa.Column('template_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_by_user_id', sa.String(), nullable=False),
    sa.Column('completed_by_user_id', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('open', 'completed', 'cancelled')", name='ck_controladoria_workflow_runs_status'),
    sa.ForeignKeyConstraint(['tenant_id', 'case_id'], ['workspace_cases.tenant_id', 'workspace_cases.id'], name='fk_controladoria_workflow_runs_case_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'completed_by_user_id'], ['users.tenant_id', 'users.id'], name='fk_controladoria_workflow_runs_completer_tenant'),
    sa.ForeignKeyConstraint(['tenant_id', 'started_by_user_id'], ['users.tenant_id', 'users.id'], name='fk_controladoria_workflow_runs_starter_tenant'),
    sa.ForeignKeyConstraint(['tenant_id', 'template_id'], ['controladoria_workflow_templates.tenant_id', 'controladoria_workflow_templates.id'], name='fk_controladoria_workflow_runs_template_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_controladoria_workflow_runs_tenant_id')
    )
    op.create_index(op.f('ix_controladoria_workflow_runs_case_id'), 'controladoria_workflow_runs', ['case_id'], unique=False)
    op.create_index(op.f('ix_controladoria_workflow_runs_status'), 'controladoria_workflow_runs', ['status'], unique=False)
    op.create_index(op.f('ix_controladoria_workflow_runs_template_id'), 'controladoria_workflow_runs', ['template_id'], unique=False)
    op.create_index(op.f('ix_controladoria_workflow_runs_tenant_id'), 'controladoria_workflow_runs', ['tenant_id'], unique=False)
    op.create_table('controladoria_workflow_template_steps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('position > 0', name='ck_controladoria_workflow_template_steps_position'),
    sa.ForeignKeyConstraint(['tenant_id', 'template_id'], ['controladoria_workflow_templates.tenant_id', 'controladoria_workflow_templates.id'], name='fk_controladoria_workflow_template_steps_template_tenant', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_controladoria_workflow_template_steps_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'template_id', 'position', name='uq_controladoria_workflow_template_steps_position')
    )
    op.create_index(op.f('ix_controladoria_workflow_template_steps_template_id'), 'controladoria_workflow_template_steps', ['template_id'], unique=False)
    op.create_index(op.f('ix_controladoria_workflow_template_steps_tenant_id'), 'controladoria_workflow_template_steps', ['tenant_id'], unique=False)
    op.create_table('public_intakes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('config_id', sa.String(), nullable=False),
    sa.Column('idempotency_hash', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('subject', sa.String(length=160), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('preferred_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_version', sa.String(length=64), nullable=False),
    sa.Column('consented_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('converted_client_id', sa.String(), nullable=True),
    sa.Column('converted_case_id', sa.String(), nullable=True),
    sa.Column('converted_by_user_id', sa.String(), nullable=True),
    sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('new', 'converted', 'archived')", name='ck_public_intakes_status'),
    sa.CheckConstraint('(converted_client_id IS NULL) = (converted_case_id IS NULL)', name='ck_public_intakes_conversion_pair'),
    sa.ForeignKeyConstraint(['tenant_id', 'config_id'], ['public_intake_configs.tenant_id', 'public_intake_configs.id'], name='fk_public_intakes_config_tenant'),
    sa.ForeignKeyConstraint(['tenant_id', 'converted_by_user_id'], ['users.tenant_id', 'users.id'], name='fk_public_intakes_converter_tenant'),
    sa.ForeignKeyConstraint(['tenant_id', 'converted_case_id'], ['workspace_cases.tenant_id', 'workspace_cases.id'], name='fk_public_intakes_case_tenant'),
    sa.ForeignKeyConstraint(['tenant_id', 'converted_client_id'], ['workspace_clients.tenant_id', 'workspace_clients.id'], name='fk_public_intakes_client_tenant'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_id', 'idempotency_hash', name='uq_public_intakes_idempotency'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_public_intakes_tenant_id')
    )
    op.create_index(op.f('ix_public_intakes_config_id'), 'public_intakes', ['config_id'], unique=False)
    op.create_index(op.f('ix_public_intakes_converted_case_id'), 'public_intakes', ['converted_case_id'], unique=False)
    op.create_index(op.f('ix_public_intakes_converted_client_id'), 'public_intakes', ['converted_client_id'], unique=False)
    op.create_index(op.f('ix_public_intakes_preferred_contact_at'), 'public_intakes', ['preferred_contact_at'], unique=False)
    op.create_index(op.f('ix_public_intakes_status'), 'public_intakes', ['status'], unique=False)
    op.create_index(op.f('ix_public_intakes_tenant_id'), 'public_intakes', ['tenant_id'], unique=False)
    op.create_table('controladoria_judicial_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('subscription_id', sa.String(), nullable=True),
    sa.Column('source_kind', sa.String(length=16), nullable=False),
    sa.Column('source_event_id', sa.String(length=200), nullable=False),
    sa.Column('dedupe_key', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source_content', sa.Text(), nullable=True),
    sa.Column('source_metadata', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('triage_status', sa.String(length=16), nullable=False),
    sa.Column('triage_note', sa.Text(), nullable=True),
    sa.Column('triaged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triaged_by_user_id', sa.String(), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source_kind IN ('manual', 'datajud')", name='ck_controladoria_judicial_events_source_kind'),
    sa.CheckConstraint("triage_status IN ('pending', 'reviewed', 'discarded')", name='ck_controladoria_judicial_events_triage_status'),
    sa.ForeignKeyConstraint(['tenant_id', 'case_id'], ['workspace_cases.tenant_id', 'workspace_cases.id'], name='fk_controladoria_judicial_events_case_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'created_by_user_id'], ['users.tenant_id', 'users.id'], name='fk_controladoria_judicial_events_creator_tenant'),
    sa.ForeignKeyConstraint(['tenant_id', 'subscription_id'], ['controladoria_monitoring_subscriptions.tenant_id', 'controladoria_monitoring_subscriptions.id'], name='fk_controladoria_judicial_events_subscription_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'triaged_by_user_id'], ['users.tenant_id', 'users.id'], name='fk_controladoria_judicial_events_triager_tenant'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'dedupe_key', name='uq_controladoria_judicial_events_dedupe'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_controladoria_judicial_events_tenant_id')
    )
    op.create_index(op.f('ix_controladoria_judicial_events_case_id'), 'controladoria_judicial_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_controladoria_judicial_events_occurred_at'), 'controladoria_judicial_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_controladoria_judicial_events_retrieved_at'), 'controladoria_judicial_events', ['retrieved_at'], unique=False)
    op.create_index(op.f('ix_controladoria_judicial_events_subscription_id'), 'controladoria_judicial_events', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_controladoria_judicial_events_tenant_id'), 'controladoria_judicial_events', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_controladoria_judicial_events_triage_status'), 'controladoria_judicial_events', ['triage_status'], unique=False)
    op.create_table('controladoria_workflow_run_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('workflow_run_id', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('resolved_by_user_id', sa.String(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(status = 'pending' AND resolved_at IS NULL AND resolved_by_user_id IS NULL) OR (status IN ('completed', 'skipped') AND resolved_at IS NOT NULL AND resolved_by_user_id IS NOT NULL)", name='ck_controladoria_workflow_run_items_resolution'),
    sa.CheckConstraint("status IN ('pending', 'completed', 'skipped')", name='ck_controladoria_workflow_run_items_status'),
    sa.CheckConstraint('position > 0', name='ck_controladoria_workflow_run_items_position'),
    sa.ForeignKeyConstraint(['tenant_id', 'resolved_by_user_id'], ['users.tenant_id', 'users.id'], name='fk_controladoria_workflow_run_items_resolver_tenant'),
    sa.ForeignKeyConstraint(['tenant_id', 'workflow_run_id'], ['controladoria_workflow_runs.tenant_id', 'controladoria_workflow_runs.id'], name='fk_controladoria_workflow_run_items_run_tenant', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_controladoria_workflow_run_items_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'workflow_run_id', 'position', name='uq_controladoria_workflow_run_items_position')
    )
    op.create_index(op.f('ix_controladoria_workflow_run_items_status'), 'controladoria_workflow_run_items', ['status'], unique=False)
    op.create_index(op.f('ix_controladoria_workflow_run_items_tenant_id'), 'controladoria_workflow_run_items', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_controladoria_workflow_run_items_workflow_run_id'), 'controladoria_workflow_run_items', ['workflow_run_id'], unique=False)
    op.create_table('fee_contracts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('document_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('terms_version', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name='ck_fee_contracts_currency'),
    sa.CheckConstraint("status IN ('draft', 'active', 'closed', 'void')", name='ck_fee_contracts_status'),
    sa.ForeignKeyConstraint(['tenant_id', 'case_id'], ['workspace_cases.tenant_id', 'workspace_cases.id'], name='fk_fee_contracts_case_tenant'),
    sa.ForeignKeyConstraint(['tenant_id', 'client_id'], ['workspace_clients.tenant_id', 'workspace_clients.id'], name='fk_fee_contracts_client_tenant'),
    sa.ForeignKeyConstraint(['tenant_id', 'created_by_user_id'], ['users.tenant_id', 'users.id'], name='fk_fee_contracts_creator_tenant'),
    sa.ForeignKeyConstraint(['tenant_id', 'document_id'], ['workspace_documents.tenant_id', 'workspace_documents.id'], name='fk_fee_contracts_document_tenant'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_fee_contracts_tenant_id')
    )
    op.create_index(op.f('ix_fee_contracts_case_id'), 'fee_contracts', ['case_id'], unique=False)
    op.create_index(op.f('ix_fee_contracts_client_id'), 'fee_contracts', ['client_id'], unique=False)
    op.create_index(op.f('ix_fee_contracts_document_id'), 'fee_contracts', ['document_id'], unique=False)
    op.create_index(op.f('ix_fee_contracts_status'), 'fee_contracts', ['status'], unique=False)
    op.create_index(op.f('ix_fee_contracts_tenant_id'), 'fee_contracts', ['tenant_id'], unique=False)
    op.create_table('signature_envelopes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('document_version', sa.Integer(), nullable=False),
    sa.Column('document_hash', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_account_reference', sa.String(length=128), nullable=False),
    sa.Column('provider_envelope_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('dispatch_status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('declined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("dispatch_status IN ('not_dispatched', 'submitted', 'unknown', 'failed')", name='ck_signature_envelopes_dispatch'),
    sa.CheckConstraint("status IN ('pending', 'signed', 'declined', 'expired')", name='ck_signature_envelopes_status'),
    sa.ForeignKeyConstraint(['tenant_id', 'created_by_user_id'], ['users.tenant_id', 'users.id'], name='fk_signature_envelopes_creator_tenant'),
    sa.ForeignKeyConstraint(['tenant_id', 'document_id'], ['workspace_documents.tenant_id', 'workspace_documents.id'], name='fk_signature_envelopes_document_tenant'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_signature_envelopes_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'provider', 'provider_account_reference', 'provider_envelope_hash', name='uq_signature_envelopes_provider_reference')
    )
    op.create_index(op.f('ix_signature_envelopes_document_id'), 'signature_envelopes', ['document_id'], unique=False)
    op.create_index(op.f('ix_signature_envelopes_status'), 'signature_envelopes', ['status'], unique=False)
    op.create_index(op.f('ix_signature_envelopes_tenant_id'), 'signature_envelopes', ['tenant_id'], unique=False)
    op.create_table('controladoria_deadline_reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('suggested_due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('suggested_basis', sa.Text(), nullable=False),
    sa.Column('assigned_user_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('suggested_by_user_id', sa.String(), nullable=False),
    sa.Column('reviewed_by_user_id', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(status = 'approved' AND reviewed_at IS NOT NULL AND reviewed_by_user_id IS NOT NULL AND task_id IS NOT NULL) OR (status IN ('suggested', 'rejected') AND task_id IS NULL)", name='ck_controladoria_deadline_reviews_human_approval'),
    sa.CheckConstraint("status IN ('suggested', 'approved', 'rejected')", name='ck_controladoria_deadline_reviews_status'),
    sa.ForeignKeyConstraint(['tenant_id', 'assigned_user_id'], ['users.tenant_id', 'users.id'], name='fk_controladoria_deadline_reviews_assignee_tenant'),
    sa.ForeignKeyConstraint(['tenant_id', 'case_id'], ['workspace_cases.tenant_id', 'workspace_cases.id'], name='fk_controladoria_deadline_reviews_case_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'event_id'], ['controladoria_judicial_events.tenant_id', 'controladoria_judicial_events.id'], name='fk_controladoria_deadline_reviews_event_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'reviewed_by_user_id'], ['users.tenant_id', 'users.id'], name='fk_controladoria_deadline_reviews_reviewer_tenant'),
    sa.ForeignKeyConstraint(['tenant_id', 'suggested_by_user_id'], ['users.tenant_id', 'users.id'], name='fk_controladoria_deadline_reviews_suggester_tenant'),
    sa.ForeignKeyConstraint(['tenant_id', 'task_id'], ['workspace_tasks.tenant_id', 'workspace_tasks.id'], name='fk_controladoria_deadline_reviews_task_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id'),
    sa.UniqueConstraint('tenant_id', 'event_id', name='uq_controladoria_deadline_reviews_event'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_controladoria_deadline_reviews_tenant_id')
    )
    op.create_index(op.f('ix_controladoria_deadline_reviews_case_id'), 'controladoria_deadline_reviews', ['case_id'], unique=False)
    op.create_index(op.f('ix_controladoria_deadline_reviews_event_id'), 'controladoria_deadline_reviews', ['event_id'], unique=False)
    op.create_index(op.f('ix_controladoria_deadline_reviews_status'), 'controladoria_deadline_reviews', ['status'], unique=False)
    op.create_index(op.f('ix_controladoria_deadline_reviews_suggested_due_at'), 'controladoria_deadline_reviews', ['suggested_due_at'], unique=False)
    op.create_index(op.f('ix_controladoria_deadline_reviews_tenant_id'), 'controladoria_deadline_reviews', ['tenant_id'], unique=False)
    op.create_table('fee_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('fee_contract_id', sa.String(), nullable=False),
    sa.Column('rule_type', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(rule_type IN ('fixed', 'hourly') AND amount IS NOT NULL AND amount > 0 AND percentage IS NULL) OR (rule_type = 'success' AND amount IS NULL AND percentage IS NOT NULL AND percentage > 0 AND percentage <= 100)", name='ck_fee_rules_value'),
    sa.CheckConstraint("rule_type IN ('fixed', 'hourly', 'success')", name='ck_fee_rules_type'),
    sa.ForeignKeyConstraint(['tenant_id', 'fee_contract_id'], ['fee_contracts.tenant_id', 'fee_contracts.id'], name='fk_fee_rules_contract_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_fee_rules_tenant_id')
    )
    op.create_index(op.f('ix_fee_rules_fee_contract_id'), 'fee_rules', ['fee_contract_id'], unique=False)
    op.create_index(op.f('ix_fee_rules_tenant_id'), 'fee_rules', ['tenant_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('fee_contract_id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('received_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'issued', 'partially_paid', 'paid', 'void', 'overdue')", name='ck_invoices_status'),
    sa.CheckConstraint('total_amount > 0 AND received_amount >= 0 AND received_amount <= total_amount', name='ck_invoices_amounts'),
    sa.ForeignKeyConstraint(['tenant_id', 'case_id'], ['workspace_cases.tenant_id', 'workspace_cases.id'], name='fk_invoices_case_tenant'),
    sa.ForeignKeyConstraint(['tenant_id', 'client_id'], ['workspace_clients.tenant_id', 'workspace_clients.id'], name='fk_invoices_client_tenant'),
    sa.ForeignKeyConstraint(['tenant_id', 'created_by_user_id'], ['users.tenant_id', 'users.id'], name='fk_invoices_creator_tenant'),
    sa.ForeignKeyConstraint(['tenant_id', 'fee_contract_id'], ['fee_contracts.tenant_id', 'fee_contracts.id'], name='fk_invoices_contract_tenant'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_invoices_tenant_id')
    )
    op.create_index(op.f('ix_invoices_case_id'), 'invoices', ['case_id'], unique=False)
    op.create_index(op.f('ix_invoices_client_id'), 'invoices', ['client_id'], unique=False)
    op.create_index(op.f('ix_invoices_fee_contract_id'), 'invoices', ['fee_contract_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index(op.f('ix_invoices_tenant_id'), 'invoices', ['tenant_id'], unique=False)
    op.create_table('signature_provider_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('envelope_id', sa.String(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('account_reference', sa.String(length=128), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('event_digest', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'envelope_id'], ['signature_envelopes.tenant_id', 'signature_envelopes.id'], name='fk_signature_provider_events_envelope_tenant'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'provider', 'account_reference', 'event_digest', name='uq_signature_provider_event_digest'),
    sa.UniqueConstraint('tenant_id', 'provider', 'account_reference', 'event_id', name='uq_signature_provider_event')
    )
    op.create_index(op.f('ix_signature_provider_events_envelope_id'), 'signature_provider_events', ['envelope_id'], unique=False)
    op.create_index(op.f('ix_signature_provider_events_tenant_id'), 'signature_provider_events', ['tenant_id'], unique=False)
    op.create_table('receivables',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('invoice_id', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'partially_paid', 'paid', 'void', 'overdue')", name='ck_receivables_status'),
    sa.CheckConstraint('amount > 0 AND paid_amount >= 0 AND paid_amount <= amount', name='ck_receivables_amounts'),
    sa.ForeignKeyConstraint(['tenant_id', 'invoice_id'], ['invoices.tenant_id', 'invoices.id'], name='fk_receivables_invoice_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id', 'sequence', name='uq_receivables_invoice_sequence'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_receivables_tenant_id')
    )
    op.create_index(op.f('ix_receivables_due_on'), 'receivables', ['due_on'], unique=False)
    op.create_index(op.f('ix_receivables_invoice_id'), 'receivables', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_receivables_status'), 'receivables', ['status'], unique=False)
    op.create_index(op.f('ix_receivables_tenant_id'), 'receivables', ['tenant_id'], unique=False)
    op.create_table('time_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('fee_contract_id', sa.String(), nullable=False),
    sa.Column('fee_rule_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rate_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'approved', 'invoiced', 'void')", name='ck_time_entries_status'),
    sa.CheckConstraint('amount >= 0', name='ck_time_entries_amount'),
    sa.CheckConstraint('duration_minutes BETWEEN 1 AND 1440', name='ck_time_entries_duration'),
    sa.ForeignKeyConstraint(['tenant_id', 'case_id'], ['workspace_cases.tenant_id', 'workspace_cases.id'], name='fk_time_entries_case_tenant'),
    sa.ForeignKeyConstraint(['tenant_id', 'created_by_user_id'], ['users.tenant_id', 'users.id'], name='fk_time_entries_creator_tenant'),
    sa.ForeignKeyConstraint(['tenant_id', 'fee_contract_id'], ['fee_contracts.tenant_id', 'fee_contracts.id'], name='fk_time_entries_contract_tenant'),
    sa.ForeignKeyConstraint(['tenant_id', 'fee_rule_id'], ['fee_rules.tenant_id', 'fee_rules.id'], name='fk_time_entries_rule_tenant'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_time_entries_tenant_id')
    )
    op.create_index(op.f('ix_time_entries_case_id'), 'time_entries', ['case_id'], unique=False)
    op.create_index(op.f('ix_time_entries_fee_contract_id'), 'time_entries', ['fee_contract_id'], unique=False)
    op.create_index(op.f('ix_time_entries_fee_rule_id'), 'time_entries', ['fee_rule_id'], unique=False)
    op.create_index(op.f('ix_time_entries_occurred_at'), 'time_entries', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_time_entries_status'), 'time_entries', ['status'], unique=False)
    op.create_index(op.f('ix_time_entries_tenant_id'), 'time_entries', ['tenant_id'], unique=False)
    op.create_table('payment_receipts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('receivable_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_account_reference', sa.String(length=128), nullable=False),
    sa.Column('provider_payment_hash', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('provider_occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('received', 'reversed')", name='ck_payment_receipts_status'),
    sa.CheckConstraint('amount > 0', name='ck_payment_receipts_amount'),
    sa.ForeignKeyConstraint(['tenant_id', 'receivable_id'], ['receivables.tenant_id', 'receivables.id'], name='fk_payment_receipts_receivable_tenant'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_payment_receipts_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'provider', 'provider_account_reference', 'provider_payment_hash', name='uq_payment_receipts_provider_payment')
    )
    op.create_index(op.f('ix_payment_receipts_receivable_id'), 'payment_receipts', ['receivable_id'], unique=False)
    op.create_index(op.f('ix_payment_receipts_tenant_id'), 'payment_receipts', ['tenant_id'], unique=False)
    op.create_table('payment_provider_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('receipt_id', sa.String(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('account_reference', sa.String(length=128), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('event_digest', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'receipt_id'], ['payment_receipts.tenant_id', 'payment_receipts.id'], name='fk_payment_provider_events_receipt_tenant'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'provider', 'account_reference', 'event_digest', name='uq_payment_provider_event_digest'),
    sa.UniqueConstraint('tenant_id', 'provider', 'account_reference', 'event_id', name='uq_payment_provider_event')
    )
    op.create_index(op.f('ix_payment_provider_events_receipt_id'), 'payment_provider_events', ['receipt_id'], unique=False)
    op.create_index(op.f('ix_payment_provider_events_tenant_id'), 'payment_provider_events', ['tenant_id'], unique=False)
    tenant_tables = (
        'operation_provider_credentials', 'public_intake_configs', 'controladoria_workflow_templates',
        'controladoria_monitoring_subscriptions', 'controladoria_workflow_runs',
        'controladoria_workflow_template_steps', 'public_intakes', 'controladoria_judicial_events',
        'controladoria_workflow_run_items', 'fee_contracts', 'signature_envelopes',
        'controladoria_deadline_reviews', 'fee_rules', 'invoices', 'signature_provider_events',
        'receivables', 'time_entries', 'payment_receipts', 'payment_provider_events',
    )
    for table in tenant_tables:
        op.execute(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY')
        op.execute(f'ALTER TABLE {table} FORCE ROW LEVEL SECURITY')
        op.execute(f"CREATE POLICY {table}_tenant_isolation ON {table} USING (tenant_id = current_setting('app.current_tenant', true)) WITH CHECK (tenant_id = current_setting('app.current_tenant', true))")
    op.execute("""
        CREATE FUNCTION public_intake_tenant_for_token(request_token_hash text) RETURNS text
        LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog, public AS $$
        SELECT tenant_id FROM public.public_intake_configs
        WHERE token_hash = request_token_hash AND enabled IS TRUE LIMIT 1 $$
    """)
    op.execute("REVOKE ALL ON FUNCTION public_intake_tenant_for_token(text) FROM PUBLIC")
    op.execute("""
        CREATE FUNCTION operation_webhook_identity(request_purpose text, request_provider text, request_account text) RETURNS text
        LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog, public AS $$
        SELECT tenant_id FROM public.operation_provider_credentials
        WHERE purpose = request_purpose AND provider = request_provider
          AND account_reference = request_account AND enabled IS TRUE LIMIT 1 $$
    """)
    op.execute("REVOKE ALL ON FUNCTION operation_webhook_identity(text, text, text) FROM PUBLIC")
    op.execute("""
        CREATE FUNCTION controladoria_monitoring_candidates(max_rows integer)
        RETURNS TABLE(subscription_id text, tenant_id text, tribunal varchar, process_number varchar, responsible_user_id text)
        LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog, public AS $$
        SELECT subscription.id, subscription.tenant_id, subscription.tribunal, subscription.process_number, cases.responsible_user_id
        FROM public.controladoria_monitoring_subscriptions subscription
        JOIN public.workspace_cases cases ON cases.tenant_id = subscription.tenant_id AND cases.id = subscription.case_id
        WHERE subscription.status = 'active'
          AND (subscription.last_checked_at IS NULL OR subscription.last_checked_at < statement_timestamp() - interval '15 minutes')
        ORDER BY subscription.last_checked_at NULLS FIRST, subscription.id
        LIMIT LEAST(GREATEST(max_rows, 1), 200) $$
    """)
    op.execute("REVOKE ALL ON FUNCTION controladoria_monitoring_candidates(integer) FROM PUBLIC")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    material_tables = (
        'public_intakes', 'controladoria_judicial_events', 'controladoria_deadline_reviews',
        'controladoria_workflow_runs', 'fee_contracts', 'time_entries', 'invoices',
        'signature_envelopes', 'payment_receipts',
    )
    if any(op.get_bind().execute(sa.text(f'SELECT count(*) FROM {table}')).scalar() for table in material_tables):
        raise RuntimeError('Refusing to discard legal operations, financial, signature or judicial history')
    for function in (
        'controladoria_monitoring_candidates(integer)',
        'operation_webhook_identity(text, text, text)',
        'public_intake_tenant_for_token(text)',
    ):
        op.execute(f'DROP FUNCTION IF EXISTS {function}')
    op.drop_index(op.f('ix_payment_provider_events_tenant_id'), table_name='payment_provider_events')
    op.drop_index(op.f('ix_payment_provider_events_receipt_id'), table_name='payment_provider_events')
    op.drop_table('payment_provider_events')
    op.drop_index(op.f('ix_payment_receipts_tenant_id'), table_name='payment_receipts')
    op.drop_index(op.f('ix_payment_receipts_receivable_id'), table_name='payment_receipts')
    op.drop_table('payment_receipts')
    op.drop_index(op.f('ix_time_entries_tenant_id'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_status'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_occurred_at'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_fee_rule_id'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_fee_contract_id'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_case_id'), table_name='time_entries')
    op.drop_table('time_entries')
    op.drop_index(op.f('ix_receivables_tenant_id'), table_name='receivables')
    op.drop_index(op.f('ix_receivables_status'), table_name='receivables')
    op.drop_index(op.f('ix_receivables_invoice_id'), table_name='receivables')
    op.drop_index(op.f('ix_receivables_due_on'), table_name='receivables')
    op.drop_table('receivables')
    op.drop_index(op.f('ix_signature_provider_events_tenant_id'), table_name='signature_provider_events')
    op.drop_index(op.f('ix_signature_provider_events_envelope_id'), table_name='signature_provider_events')
    op.drop_table('signature_provider_events')
    op.drop_index(op.f('ix_invoices_tenant_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_fee_contract_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_client_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_case_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_fee_rules_tenant_id'), table_name='fee_rules')
    op.drop_index(op.f('ix_fee_rules_fee_contract_id'), table_name='fee_rules')
    op.drop_table('fee_rules')
    op.drop_index(op.f('ix_controladoria_deadline_reviews_tenant_id'), table_name='controladoria_deadline_reviews')
    op.drop_index(op.f('ix_controladoria_deadline_reviews_suggested_due_at'), table_name='controladoria_deadline_reviews')
    op.drop_index(op.f('ix_controladoria_deadline_reviews_status'), table_name='controladoria_deadline_reviews')
    op.drop_index(op.f('ix_controladoria_deadline_reviews_event_id'), table_name='controladoria_deadline_reviews')
    op.drop_index(op.f('ix_controladoria_deadline_reviews_case_id'), table_name='controladoria_deadline_reviews')
    op.drop_table('controladoria_deadline_reviews')
    op.drop_index(op.f('ix_signature_envelopes_tenant_id'), table_name='signature_envelopes')
    op.drop_index(op.f('ix_signature_envelopes_status'), table_name='signature_envelopes')
    op.drop_index(op.f('ix_signature_envelopes_document_id'), table_name='signature_envelopes')
    op.drop_table('signature_envelopes')
    op.drop_index(op.f('ix_fee_contracts_tenant_id'), table_name='fee_contracts')
    op.drop_index(op.f('ix_fee_contracts_status'), table_name='fee_contracts')
    op.drop_index(op.f('ix_fee_contracts_document_id'), table_name='fee_contracts')
    op.drop_index(op.f('ix_fee_contracts_client_id'), table_name='fee_contracts')
    op.drop_index(op.f('ix_fee_contracts_case_id'), table_name='fee_contracts')
    op.drop_table('fee_contracts')
    op.drop_index(op.f('ix_controladoria_workflow_run_items_workflow_run_id'), table_name='controladoria_workflow_run_items')
    op.drop_index(op.f('ix_controladoria_workflow_run_items_tenant_id'), table_name='controladoria_workflow_run_items')
    op.drop_index(op.f('ix_controladoria_workflow_run_items_status'), table_name='controladoria_workflow_run_items')
    op.drop_table('controladoria_workflow_run_items')
    op.drop_index(op.f('ix_controladoria_judicial_events_triage_status'), table_name='controladoria_judicial_events')
    op.drop_index(op.f('ix_controladoria_judicial_events_tenant_id'), table_name='controladoria_judicial_events')
    op.drop_index(op.f('ix_controladoria_judicial_events_subscription_id'), table_name='controladoria_judicial_events')
    op.drop_index(op.f('ix_controladoria_judicial_events_retrieved_at'), table_name='controladoria_judicial_events')
    op.drop_index(op.f('ix_controladoria_judicial_events_occurred_at'), table_name='controladoria_judicial_events')
    op.drop_index(op.f('ix_controladoria_judicial_events_case_id'), table_name='controladoria_judicial_events')
    op.drop_table('controladoria_judicial_events')
    op.drop_index(op.f('ix_public_intakes_tenant_id'), table_name='public_intakes')
    op.drop_index(op.f('ix_public_intakes_status'), table_name='public_intakes')
    op.drop_index(op.f('ix_public_intakes_converted_client_id'), table_name='public_intakes')
    op.drop_index(op.f('ix_public_intakes_preferred_contact_at'), table_name='public_intakes')
    op.drop_index(op.f('ix_public_intakes_converted_case_id'), table_name='public_intakes')
    op.drop_index(op.f('ix_public_intakes_config_id'), table_name='public_intakes')
    op.drop_table('public_intakes')
    op.drop_index(op.f('ix_controladoria_workflow_template_steps_tenant_id'), table_name='controladoria_workflow_template_steps')
    op.drop_index(op.f('ix_controladoria_workflow_template_steps_template_id'), table_name='controladoria_workflow_template_steps')
    op.drop_table('controladoria_workflow_template_steps')
    op.drop_index(op.f('ix_controladoria_workflow_runs_tenant_id'), table_name='controladoria_workflow_runs')
    op.drop_index(op.f('ix_controladoria_workflow_runs_template_id'), table_name='controladoria_workflow_runs')
    op.drop_index(op.f('ix_controladoria_workflow_runs_status'), table_name='controladoria_workflow_runs')
    op.drop_index(op.f('ix_controladoria_workflow_runs_case_id'), table_name='controladoria_workflow_runs')
    op.drop_table('controladoria_workflow_runs')
    op.drop_index(op.f('ix_controladoria_monitoring_subscriptions_tenant_id'), table_name='controladoria_monitoring_subscriptions')
    op.drop_index(op.f('ix_controladoria_monitoring_subscriptions_status'), table_name='controladoria_monitoring_subscriptions')
    op.drop_index(op.f('ix_controladoria_monitoring_subscriptions_case_id'), table_name='controladoria_monitoring_subscriptions')
    op.drop_table('controladoria_monitoring_subscriptions')
    op.drop_index(op.f('ix_controladoria_workflow_templates_tenant_id'), table_name='controladoria_workflow_templates')
    op.drop_index(op.f('ix_controladoria_workflow_templates_is_active'), table_name='controladoria_workflow_templates')
    op.drop_index(op.f('ix_controladoria_workflow_templates_case_type'), table_name='controladoria_workflow_templates')
    op.drop_table('controladoria_workflow_templates')
    op.drop_index(op.f('ix_public_intake_configs_tenant_id'), table_name='public_intake_configs')
    op.drop_table('public_intake_configs')
    op.drop_index(op.f('ix_operation_provider_credentials_tenant_id'), table_name='operation_provider_credentials')
    op.drop_table('operation_provider_credentials')
    # ### end Alembic commands ###
